### ISSUE TITLE
Chat Network- Can only send messages from one node to the other.

### ISSUE THREAD

**Issue by DevHenry** [raspberrypilearning/networking-lessons#23]
When using the chat network all is well however i can only send messages from one node, lets call it Node 1, to the other, Node 2. 

So I can send messages from Node 1 to Node 2, but not Node 2 to Node 1. I get the error  "NameError: name 'hi' is not defined" on Node 2,where 'hi' is the message, and the error 'CONNECTION LOST' on node 1.

**Comment by whaleygeek** [comment]
Yes, that's because it uses TCP, which is connection oriented. The Chat was only ever intended to be a point to point network example, as a way to get children to have a reason to learn about IP addresses, netmasks, port numbers, etc etc.

I always had a view when I wrote this that I would develop a multicast UDP version of it as well, but never got round to it, as the point to point TCP version was always 'enough' for the classes I was teaching.
